=== go4retro/tcpser4j/TCPSerial.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Settings">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="PhoneBook" minOccurs="0"/>
				<xsd:element ref="ModemPool" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="ModemPool">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Line" minOccurs="0"/>
				<xsd:element name="TemplateModem" type="ModemInfo" minOccurs="0"/>
				<xsd:element name="Modem" type="ModemInfo" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Line">
		<xsd:complexType>
			<xsd:attribute name="port" type="xsd:integer"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="ModemInfo">
		<xsd:sequence>
			<xsd:element name="Initialization" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Message" type="MessageInfo" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="PhoneBook" minOccurs="0"/>
			<xsd:element name="CaptiveModem" type="ModemInfo" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string"/>
		<xsd:attribute name="device" type="xsd:string"/>
		<xsd:attribute name="speed" type="xsd:integer"/>
		<xsd:attribute name="parity" type="xsd:string"/>
		<xsd:attribute name="stopbits" type="xsd:integer"/>
		<xsd:attribute name="invertDCD" type="xsd:boolean"/>
	</xsd:complexType>
	<xsd:complexType name="MessageInfo">
		<xsd:attribute name="action" type="ActionList"/>
		<xsd:attribute name="direction" type="DirectionList"/>
		<xsd:attribute name="location" type="xsd:string"/>
	</xsd:complexType>
	<xsd:simpleType name="ActionList">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="answer"/>
			<xsd:enumeration value="connect"/>
			<xsd:enumeration value="busy"/>
			<xsd:enumeration value="inactivity"/>
			<xsd:enumeration value="no_answer"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DirectionList">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="local"/>
			<xsd:enumeration value="remote"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="PhoneBook">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Entry" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Entry">
		<xsd:complexType>
			<xsd:attribute name="number" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== go4retro/tcpser4j/config-linux.xml
<Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TCPSerial.xsd">
	<!-- Master Phone Book. Items shared among pools can be placed here-->
	<PhoneBook>
		<Entry number="madworld" value="murdworld.bounceme.net:23"/>
		<Entry number="addixion" value="addixion.hopto.org:23"/>
		<Entry number="antidote" value="antidote.hopto.org:23"/>
		<Entry number="carbonek" value="65.40.213.24:23"/>
		<Entry number="dragonseye" value="dragonseye.dyndns.org:6400"/>
		<Entry number="elmstreet" value="elmstreet.dyndns.org:23"/>
		<Entry number="forgottenrealms" value="forgottenrealmsbbs.org:23"/>
		<Entry number="jammingsignal" value="bbs.jammingsignal.com:23"/>
		<Entry number="hidden" value="the-hidden.hopto.org:23"/>
		<Entry number="laststand" value="laststandbbs.net:23"/>
		<Entry number="lostcaverns" value="lostcavernsbbs.dyndns.org:6001"/>
		<Entry number="lostcaverns1" value="lostcavernsbbs.dyndns.org:6001"/>
		<Entry number="lostcaverns2" value="lostcavernsbbs.dyndns.org:6002"/>
		<Entry number="renaissancecity" value="renaissancecitybbs.dyndns.tv:23"/>
		<Entry number="rkbbs" value="rkbbs.net:23"/>
	</PhoneBook>
	<!-- You can have multiple Multiple ModemPools-->
	<ModemPool>
		<!-- You can leave Line out for outbound only system -->
		<Line port="6400"/>
		<!-- Put any default stuff here that applies to all modems-->
		<TemplateModem>
			<!--Default Initialization Parms-->
			<!--<Initialization>s0=1</Initialization>-->
			<!--
				 Below are a few examples of EventActions, which replace simple Messages.
				 o type can be one of: 
				 	file				send a local text file to inbound or outbound connection
				 	url				send the data from a url to inbound or outbound connection
				 	audio			play a references WAV audio file
				 	java			run a java class and send output to inbound or outbound connection (not implemented yet)
				 	exec			run local app and send output to inbound or oubound connection (not fully implemented yet)
				 o action can be one of:
				 	pre_answer	before CONNECT line is sent
				 	answer		after CONNECT line is sent
				 	pre_connect	before CONNECT line is sent
				 	connect		after CONNECT line is sent
				 	dial			when the modem goes to dial.
				 	hangup		when the modem hangs up
				 	busy			busy
				 	no_answer	no answer
				 	off_hook		modem is taken off hook
				 	on_hook		modem is placed on hook
				 	cmd_mode	modem is placed into command mode
				 	data_mode	modem is placed into data mode
				 	ring			RING signal is asserted
				 o direction can be one of:
				 	local			send data to modem side
				 	remote		send data to line side
				 o content 
				 	the URL, filename, application start, etc.  This can contain variables that are replaced
				 	at time of execution.  For now, the following vars are supported:
				 					${direction}	0 for none, 1 for outgoing, 2 for incoming
				 					${speed}		speed of connection
				 					${number}		for outgoing calls, this is the number/name dialed, incoming is last number
				 					${number.method}	T for T, P for P, ' ' for default
				 					
				 	If you would like more, let me know.  They are pretty easy to add
				 o iterations is how many times to repeat this.  Only implemented on audio at present
				 o asynchronous is whether system should wait for completion.  Only implemented on audio at present
				 	true
				 	false
				 
				 All template Actions are processed before any specific modem actions.  
				 
				 You can have more than one EventAction per event.  They are processed in order listed in the file.
			-->
			<!--
			<EventAction type="file" action="pre_answer" direction="local" content="local_answer.txt"/>
			<EventAction type="url" action="answer" direction="remote" content="http://url.to.file"/>
			<EventAction type="audio" action="off_hook" direction="local" content="dialtone.wav" iterations="1" asynchronous="false"/>
			<EventAction type="audio" action="dial" direction="local" content="dtmf.wav" iterations="1" asynchronous="false"/>
			<EventAction type="audio" action="pre_connect" direction="local" content="negotiate.wav" iterations="1" asynchronous="false"/>
			<EventAction type="audio" action="connect" direction="local" content="ONLINE.wav" iterations="1" asynchronous="false"/>
			-->
			<!--Default Phone Book entries.  These are shared among the Pool-->
			<!--
			<PhoneBook>
				<Entry number="5551212" value="localhost:7"/>
			</PhoneBook>
			-->
		</TemplateModem>
		<!-- You can have multiple modems per ModemPool.  They will all share the same IP port for incoming calls.-->
		<!-- Modems all default to 38400 bps, unless specified-->
		<!-- To set up a Remote RS232 port, use the next line.  
		     Also remember to run org.jbrain.tcpser4j.RS232Forwarder on remote server before running tcpser4j 
		-->
		<!--<Modem type="remote232" device="hostname:port">-->
		<!-- To set up an inbound port to act like the DCE side of a modem (e.g., for the VICE emulator), use the next line-->
		<!--<Modem type="ip232" device="25232">-->
		<!-- for a regular RS232 port, use the next Modem line-->
		<!-- device is platform specific, COM1-4 for PC, /dev/ttyS? for UNIX, etc.-->
		<Modem type="rs232" device="/dev/ttyS1" speed="38400">
			<!-- Per modem init string.  If DefaultInit is also specified, per-modem init is added to end of default -->
			<Initialization>s0=2</Initialization>
			<!-- You can have more than one Init line.  It's useful to quickly comment out a specific command-->
			<!--note that the ampersand is a special char in XML, so it needs to be escaped-->
			<!--
				<Initialization>s0=2</Initialization>
				<Initialization>&amp;k0</Initialization>
				<Initialization>l1</Initialization>
				<Initialization>m3</Initialization>
				<Initialization>s3=13</Initialization>
			-->
			<!-- Per modem event message files.  See section in TemplateModem for more details -->
			<!-- Per modem phone book.  This book is searched first, then the Pool, then the master book -->
			<!--
			<PhoneBook>
				<Entry number="home" value="dilbert"/>
			</PhoneBook>
			-->
		</Modem>
	</ModemPool>
</Settings>
